[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
# MacOS rebind left alt to meta
option_as_alt = "Both"
dynamic_title = true
dynamic_padding = true

[window.dimensions]
columns = 88
lines = 28

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

