[general]
import = ["~/.config/alacritty/themes/rose-pine.toml"]

[window]
# MacOS rebind left alt to meta
option_as_alt = "Both"
dynamic_title = true
dynamic_padding = true

[window.dimensions]
columns = 88
lines = 28

[font]
size = 18

[font.normal]
family = "Hack Nerd Font"

